### ISSUE TITLE
Error: Invalid Protocol

### ISSUE THREAD

**Issue by ForsakenHarmony** [dandv/meteor-http-more#3]
```
return HTTP.call(method, url, options, callback);
```

url: https://steamcommunity.com/mobileconf/conf?p=android:afdc10bb-f5e3-10bb-10bb-10bbf5e35c5f&a=76561198041201900&k=VPPkuxLKe8bMt4AYhyRwCqmFjms%3D&t=1458408316&m=android&tag=conf

```
C:\Users\ArmyOfAnarchists\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:278
                        throw(ex);
                              ^
Error: Invalid protocol
    at Object.Future.wait (.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:398:15)
    at Object.call (packages/meteor/helpers.js:119:1)
    at Function.request (server/SteamAuth/SteamWeb.js:19:17)
    at SteamGuardAccount.fetchConfirmations (server/SteamAuth/SteamGuardAccount.js:95:29)
    at server/test.js:32:28
    at .meteor\local\build\programs\server\boot.js:249:5
    - - - - -
    at Request.init (.meteor\packages\dandv_http-more\1.0.7_1\npm\node_modules\request\request.js:334:51)
    at Request.onResponse (.meteor\packages\dandv_http-more\1.0.7_1\npm\node_modules\request\request.js:809:10)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1689:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1584:20)
    at CleartextStream.read [as _read] (tls.js:514:12)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
```

**Comment by ForsakenHarmony** [comment]
Alright, apparently it's a redirect that redirects to steamapp://
you can close it
